name: Create Release Branch
run-name: Create Release Branch ${{ inputs.version }} ${{ inputs.citag }}

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version. Format: <major>.<minor>'
        required: true
      citag:
        description: 'Optional tag to identify runs via the API. Displayed in run name.'
        required: false
        default: ''
        

jobs:
  release-branch:
    uses: eclipse-set/build/.github/workflows/release-branch.yml@main
    permissions:
      contents: write
    with:
      version: ${{ inputs.version }}
      target: "java/org.eclipse.set.browser.releng.target/org.eclipse.set.browser.releng.target.target"
